# Replaced by .mise.toml - this file is kept for backwards compatibility
# Use 'mise install' instead of 'aftman install'

[tools]
rojo = "rojo-rbx/rojo@7.5.1"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.25.0"
stylua = "JohnnyMorganz/StyLua@0.18.2" 