[package]
name = "yourusername/game-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Testing and core utilities
TestEZ = "roblox/testez@0.4.1"
Promise = "evaera/promise@4.0.0"

# Game framework packages  
Matter = "matter-ecs/matter@0.8.5"          # ECS framework
Reflex = "littensy/reflex@4.3.1"           # State management  
ProfileStore = "vyon/profilestore@1.0.3"   # Data persistence (shared realm fork)

# Note: Signal, Maid, and Sift still manually managed in src/Shared/Libraries/
# Note: Matter requires workaround in Locations.getPackage() due to nested package structure 