return {
    zones = {
        spawn_world = {
            id = "spawn_world",
            kind = "world",
            display_name = "Spawn World",
            order = 1,
        },
        spawn_island = {
            id = "spawn_island",
            kind = "island",
            parent = "spawn_world",
            display_name = "Spawn Island",
            order = 1,
            primary_area = "Spawn",
        },
        meadow_island = {
            id = "meadow_island",
            kind = "island",
            parent = "spawn_world",
            display_name = "Meadow Island",
            order = 2,
            primary_area = "Meadow",
        },
        Spawn = {
            id = "Spawn",
            kind = "area",
            element = "grass", -- biome RPS (elements.lua biome)
            -- ZONE LEVEL (Jason): the base level of this zone's content. Crystals stamp
            -- MiningLevel = zone_level + size offset (S/M/L = +0/+1/+2, mirroring enemy
            -- rank_offset); XP diminishes vs out-leveled targets (leveling.xp_level_scale).
            zone_level = 1, -- earth tier (homeworld spans 1-4; heaven/hell realms take 5+)
            mining_currency = "grass_coins", -- what the zone's ore PAYS (area_coins rewards resolve here)
            parent = "spawn_island",
            display_name = "Spawn Area",
            order = 1,
            unlock = {
                unlocked_by_default = true,
            },
            boosts = {},
            synthetic = {
                center = { x = 0, y = 0, z = 0 },
                size = { x = 160, y = 4, z = 160 },
                floor_y = 0,
                spawn_position = { x = 0, y = 3, z = 0 },
                egg_stands = {
                    {
                        egg_id = "earth_egg",
                        spawn_id = "BasicEarth",
                        position = { x = 0, y = 0.5, z = -22 },
                    },
                },
            },
        },
        Meadow = {
            id = "Meadow",
            kind = "area",
            element = "grass", -- biome RPS (elements.lua biome)
            zone_level = 1, -- earth tier, same as Spawn (boost island, not a step up)
            mining_currency = "grass_coins", -- what the zone's ore PAYS (area_coins rewards resolve here)
            parent = "meadow_island",
            display_name = "Meadow",
            order = 2,
            unlock = {
                required_zone = "Spawn",
                unlocked_by_default = false,
                currency = "crystals",
                -- Meadow grants a PERMANENT +10% coins boost, so it must not be near-free.
                -- ~3 min of grass mining at the fresh-squad rate.
                cost = 2000,
            },
            boosts = {
                coins = 1.1,
            },
            synthetic = {
                center = { x = 220, y = 0, z = 0 },
                size = { x = 160, y = 4, z = 160 },
                floor_y = 0,
                spawn_position = { x = 220, y = 4, z = 0 },
                egg_stands = {},
            },
        },
        Heaven_2_Ice = {
            id = "Heaven_2_Ice",
            kind = "area",
            element = "ice",
            zone_level = 6,
            mining_currency = "ice_coins",
            display_name = "Aurora Frost",
            order = 15,
            unlock = {
                unlocked_by_default = false,
                required_zone = "Desert",
                currency = "ice_coins",
                cost = 500000,
            },
            boosts = {},
            synthetic = {
                center = { x = -374, y = 4000, z = 377 },
                size = { x = 321, y = 4, z = 338 },
                floor_y = 4000.5,
                spawn_position = { x = -374, y = 4006, z = 377 },
                egg_stands = {},
            },
        },
        Heaven_2_Desert = {
            id = "Heaven_2_Desert",
            kind = "area",
            element = "desert",
            zone_level = 6,
            mining_currency = "desert_coins",
            display_name = "Aurora Sands",
            order = 16,
            unlock = {
                unlocked_by_default = false,
                required_zone = "Desert",
                currency = "desert_coins",
                cost = 500000,
            },
            boosts = {},
            synthetic = {
                center = { x = -126, y = 4000, z = 474 },
                size = { x = 331, y = 4, z = 318 },
                floor_y = 4000.5,
                spawn_position = { x = -126, y = 4006, z = 474 },
                egg_stands = {},
            },
        },
        Heaven_2_Grass = {
            id = "Heaven_2_Grass",
            kind = "area",
            element = "grass",
            zone_level = 6,
            mining_currency = "grass_coins",
            display_name = "Aurora Grove",
            order = 17,
            unlock = {
                unlocked_by_default = false,
                required_zone = "Desert",
                currency = "grass_coins",
                cost = 500000,
            },
            boosts = {},
            synthetic = {
                center = { x = -150, y = 4000, z = 266 },
                size = { x = 351, y = 4, z = 278 },
                floor_y = 4000.5,
                spawn_position = { x = -150, y = 4006, z = 266 },
                egg_stands = {},
            },
        },
        Hell_2_Lava = {
            id = "Hell_2_Lava",
            kind = "area",
            element = "lava",
            zone_level = 6,
            mining_currency = "lava_coins",
            display_name = "Frozen Lava",
            order = 18,
            unlock = {
                unlocked_by_default = false,
                required_zone = "Desert",
                currency = "lava_coins",
                cost = 500000,
            },
            boosts = {},
            synthetic = {
                center = { x = -206, y = -3999, z = 67 },
                size = { x = 361, y = 4, z = 458 },
                floor_y = -3998.5,
                spawn_position = { x = -206, y = -3993, z = 67 },
                egg_stands = {},
            },
        },
        Hell_2_Ice = {
            id = "Hell_2_Ice",
            kind = "area",
            element = "ice",
            zone_level = 6,
            mining_currency = "ice_coins",
            display_name = "Frozen Frost",
            order = 19,
            unlock = {
                unlocked_by_default = false,
                required_zone = "Desert",
                currency = "ice_coins",
                cost = 500000,
            },
            boosts = {},
            synthetic = {
                center = { x = -374, y = -3999, z = 377 },
                size = { x = 321, y = 4, z = 338 },
                floor_y = -3998.5,
                spawn_position = { x = -374, y = -3993, z = 377 },
                egg_stands = {},
            },
        },
        Hell_2_Desert = {
            id = "Hell_2_Desert",
            kind = "area",
            element = "desert",
            zone_level = 6,
            mining_currency = "desert_coins",
            display_name = "Frozen Sands",
            order = 20,
            unlock = {
                unlocked_by_default = false,
                required_zone = "Desert",
                currency = "desert_coins",
                cost = 500000,
            },
            boosts = {},
            synthetic = {
                center = { x = -126, y = -3999, z = 474 },
                size = { x = 331, y = 4, z = 318 },
                floor_y = -3998.5,
                spawn_position = { x = -126, y = -3993, z = 474 },
                egg_stands = {},
            },
        },
        Hell_2_Grass = {
            id = "Hell_2_Grass",
            kind = "area",
            element = "grass",
            zone_level = 6,
            mining_currency = "grass_coins",
            display_name = "Frozen Grove",
            order = 21,
            unlock = {
                unlocked_by_default = false,
                required_zone = "Desert",
                currency = "grass_coins",
                cost = 500000,
            },
            boosts = {},
            synthetic = {
                center = { x = -150, y = -3999, z = 266 },
                size = { x = 351, y = 4, z = 278 },
                floor_y = -3998.5,
                spawn_position = { x = -150, y = -3993, z = 266 },
                egg_stands = {},
            },
        },
    },
}
