--[[
    build_info — GENERATED by scripts/stamp_build.sh (mise run stamp). Do NOT
    hand-edit: it's overwritten on every build/publish. Shows on the BootLoader
    load screen so a published build is identifiable at a glance. Times are
    Mountain (America/Denver, DST-correct). Committed with the LAST stamp so dev
    sessions / CI have a value; the publish tasks re-stamp it fresh.
]]
return {
    version = "0.1.0",
    commit = "ab2a10f1",
    branch = "main",
    commit_date = "2026-06-29 10:57 AM MDT", -- when the running code was committed
    built_at = "2026-06-29 10:58 AM MDT", -- when this build was stamped (publish time)
    dirty = false, -- uncommitted changes present at stamp time
}
