--[[
    pet_thumbnail_assets — GENERATED by scripts/gen_pet_thumbnails.js from
    scripts/pet_thumbnail_ids.json. DO NOT EDIT BY HAND. Re-run `mise run gen-pet-thumbnails`
    after uploading/resolving thumbnails (scripts/upload_pet_thumbnails.js).

    Resolved flat IMAGE content ids for inventory-card thumbnails. The card prefers these
    (a texture — no per-frame ViewportFrame render) and falls back to the baked ViewportFrame
    when an id is absent. pets[petType][variant] / pets[petType][variant__huge] / eggs[eggType].
]]

local function id(n)
    return "rbxassetid://" .. n
end

return {
    pets = {
        ["abyssal_wyrm"] = {
            ["basic"] = id(105394355425851),
            ["golden"] = id(97610625399961),
            ["rainbow"] = id(105394355425851),
        },
        ["ash_roc"] = {
            ["basic"] = id(126599530022566),
            ["golden"] = id(130021741948767),
            ["rainbow"] = id(126599530022566),
        },
        ["ashfeather_phoenix"] = {
            ["basic"] = id(118152682535745),
            ["golden"] = id(110481029820828),
            ["rainbow"] = id(118152682535745),
        },
        ["ashmane_lion"] = {
            ["basic"] = id(81746669615812),
            ["golden"] = id(133069105234494),
            ["rainbow"] = id(81746669615812),
        },
        ["aurora_dove"] = {
            ["basic"] = id(79580655558950),
            ["golden"] = id(87513671084960),
            ["rainbow"] = id(79580655558950),
        },
        ["aurora_dragon"] = {
            ["basic"] = id(76232091257215),
            ["golden"] = id(109185800773431),
            ["rainbow"] = id(76232091257215),
        },
        ["aurora_fox"] = {
            ["basic"] = id(91204861852621),
            ["golden"] = id(133210005699377),
            ["rainbow"] = id(91204861852621),
        },
        ["aurora_leviathan"] = {
            ["basic"] = id(99266399523523),
            ["golden"] = id(104956815483275),
            ["rainbow"] = id(99266399523523),
        },
        ["bear"] = {
            ["basic"] = id(132898172629788),
            ["golden"] = id(136779094190302),
            ["rainbow"] = id(132898172629788),
        },
        ["black_ice_leviathan"] = {
            ["basic"] = id(75529001594380),
            ["golden"] = id(109718682132004),
            ["rainbow"] = id(75529001594380),
        },
        ["black_seraph"] = {
            ["basic"] = id(124830786102910),
            ["golden"] = id(75270404867134),
            ["rainbow"] = id(124830786102910),
        },
        ["blightlamb"] = {
            ["basic"] = id(134788157102235),
            ["golden"] = id(128504933441916),
            ["rainbow"] = id(134788157102235),
        },
        ["bloomlamb"] = {
            ["basic"] = id(105045149735810),
            ["golden"] = id(94807053083344),
            ["rainbow"] = id(105045149735810),
        },
        ["bloomspirit_lamb"] = {
            ["basic"] = id(75557644578840),
            ["golden"] = id(93871476446901),
            ["rainbow"] = id(75557644578840),
        },
        ["brimstone_salamander"] = {
            ["basic"] = id(74377905542360),
            ["golden"] = id(129838951095980),
            ["rainbow"] = id(74377905542360),
        },
        ["bunny"] = {
            ["basic"] = id(86015752579339),
            ["golden"] = id(118293906514573),
            ["rainbow"] = id(86015752579339),
        },
        ["carrion_scarab"] = {
            ["basic"] = id(119013107088989),
            ["golden"] = id(109245649471200),
            ["rainbow"] = id(119013107088989),
        },
        ["cinderling_imp"] = {
            ["basic"] = id(98615522952678),
            ["golden"] = id(107018379137294),
            ["rainbow"] = id(98615522952678),
        },
        ["coronal_cherub"] = {
            ["basic"] = id(88767858148542),
            ["golden"] = id(81528263606985),
            ["rainbow"] = id(88767858148542),
        },
        ["crystalbark_stag"] = {
            ["basic"] = id(79652786339903),
            ["golden"] = id(86343124783765),
            ["rainbow"] = id(79652786339903),
        },
        ["dawn_camel"] = {
            ["basic"] = id(117936718721076),
            ["golden"] = id(122636500171806),
            ["rainbow"] = id(117936718721076),
        },
        ["dawnfire_phoenix"] = {
            ["basic"] = id(132097618429068),
            ["golden"] = id(76182978528458),
            ["rainbow"] = id(132097618429068),
        },
        ["deadfire_phoenix"] = {
            ["basic"] = id(80305773011759),
            ["golden"] = id(128046744698667),
            ["rainbow"] = id(80305773011759),
        },
        ["doggy"] = {
            ["basic"] = id(138165368211446),
            ["golden"] = id(126156854984685),
            ["rainbow"] = id(138165368211446),
        },
        ["dragon"] = {
            ["basic"] = id(101613154333266),
            ["golden"] = id(110690957767384),
            ["rainbow"] = id(101613154333266),
        },
        ["dread_couatl"] = {
            ["basic"] = id(72558702818239),
            ["golden"] = id(88443802656767),
            ["rainbow"] = id(72558702818239),
        },
        ["dread_fox"] = {
            ["basic"] = id(120318087700480),
            ["golden"] = id(73092628721770),
            ["rainbow"] = id(120318087700480),
        },
        ["dread_hare"] = {
            ["basic"] = id(74033750782847),
            ["golden"] = id(107718256123233),
            ["rainbow"] = id(74033750782847),
        },
        ["dread_owl"] = {
            ["basic"] = id(110005218949980),
            ["golden"] = id(94707096049963),
            ["rainbow"] = id(110005218949980),
        },
        ["dust_camel"] = {
            ["basic"] = id(93017452970741),
            ["golden"] = id(112025343607492),
            ["rainbow"] = id(93017452970741),
        },
        ["emberling_cherub"] = {
            ["basic"] = id(100104061128272),
            ["golden"] = id(78898939057620),
            ["rainbow"] = id(100104061128272),
        },
        ["empyreal_couatl"] = {
            ["basic"] = id(116808476791394),
            ["golden"] = id(77815053649889),
            ["rainbow"] = id(116808476791394),
        },
        ["empyrean_dragon"] = {
            ["basic"] = id(89883939065664),
            ["golden"] = id(121623796091249),
            ["rainbow"] = id(89883939065664),
        },
        ["frostblight_lamb"] = {
            ["basic"] = id(140411132928255),
            ["golden"] = id(137801343514369),
            ["rainbow"] = id(140411132928255),
        },
        ["frostbrand_salamander"] = {
            ["basic"] = id(134469430529076),
            ["golden"] = id(76142885541916),
            ["rainbow"] = id(134469430529076),
        },
        ["frostcinder_imp"] = {
            ["basic"] = id(121951797391866),
            ["golden"] = id(130708840494733),
            ["rainbow"] = id(121951797391866),
        },
        ["frostdust_camel"] = {
            ["basic"] = id(123575752532636),
            ["golden"] = id(93140659498044),
            ["rainbow"] = id(123575752532636),
        },
        ["frostgrave_ent"] = {
            ["basic"] = id(107786605592741),
            ["golden"] = id(126375420327281),
            ["rainbow"] = id(107786605592741),
        },
        ["frostlight_doe"] = {
            ["basic"] = id(114210893563381),
            ["golden"] = id(138960441247895),
            ["rainbow"] = id(114210893563381),
        },
        ["frostlight_hare"] = {
            ["basic"] = id(107456862601107),
            ["golden"] = id(122785845832141),
            ["rainbow"] = id(107456862601107),
        },
        ["gilded_sphinx"] = {
            ["basic"] = id(139993087832876),
            ["golden"] = id(118684911565527),
            ["rainbow"] = id(139993087832876),
        },
        ["glacial_bear"] = {
            ["basic"] = id(111693557323085),
            ["golden"] = id(136599935044269),
            ["rainbow"] = id(111693557323085),
        },
        ["glacial_seraph"] = {
            ["basic"] = id(114703205158408),
            ["golden"] = id(101262186672837),
            ["rainbow"] = id(114703205158408),
        },
        ["glass_sphinx"] = {
            ["basic"] = id(82214521047015),
            ["golden"] = id(100046018172597),
            ["rainbow"] = id(82214521047015),
        },
        ["gloom_hare"] = {
            ["basic"] = id(89177278490447),
            ["golden"] = id(106504138945967),
            ["rainbow"] = id(89177278490447),
        },
        ["gloom_jackal"] = {
            ["basic"] = id(140400841991548),
            ["golden"] = id(115078743555329),
            ["rainbow"] = id(140400841991548),
        },
        ["goldleaf_stag"] = {
            ["basic"] = id(87498939054141),
            ["golden"] = id(98202750376594),
            ["rainbow"] = id(87498939054141),
        },
        ["gravefrost_owl"] = {
            ["basic"] = id(91918610711175),
            ["golden"] = id(89036867371886),
            ["rainbow"] = id(91918610711175),
        },
        ["gravewood_ent"] = {
            ["basic"] = id(121598238267038),
            ["golden"] = id(108620030989512),
            ["rainbow"] = id(121598238267038),
        },
        ["halo_hare"] = {
            ["basic"] = id(126045475952644),
            ["golden"] = id(105604090481196),
            ["rainbow"] = id(126045475952644),
        },
        ["hoarfrost_phoenix"] = {
            ["basic"] = id(87991721985832),
            ["golden"] = id(71267854889152),
            ["rainbow"] = id(87991721985832),
        },
        ["icerot_stag"] = {
            ["basic"] = id(97905820660842),
            ["golden"] = id(114765493146860),
            ["rainbow"] = id(97905820660842),
        },
        ["kitty"] = {
            ["basic"] = id(109096120035326),
            ["golden"] = id(106255845993455),
            ["rainbow"] = id(109096120035326),
        },
        ["lance_seraph"] = {
            ["basic"] = id(103467096045656),
            ["golden"] = id(96466354878167),
            ["rainbow"] = id(103467096045656),
        },
        ["lightleaf_hare"] = {
            ["basic"] = id(139389852735214),
            ["golden"] = id(80892827935744),
            ["rainbow"] = id(139389852735214),
        },
        ["lumen_salamander"] = {
            ["basic"] = id(84143492516331),
            ["golden"] = id(92169333930749),
            ["rainbow"] = id(84143492516331),
        },
        ["mirage_jackal"] = {
            ["basic"] = id(90052768512443),
            ["golden"] = id(131724771561930),
            ["rainbow"] = id(90052768512443),
        },
        ["mirage_meerkat"] = {
            ["basic"] = id(97681032634157),
            ["golden"] = id(71768088457260),
            ["rainbow"] = id(97681032634157),
        },
        ["phantom_jackal"] = {
            ["basic"] = id(87816495826130),
            ["golden"] = id(98737039707791),
            ["rainbow"] = id(87816495826130),
        },
        ["prism_fox"] = {
            ["basic"] = id(140292224862725),
            ["golden"] = id(76537372691743),
            ["rainbow"] = id(140292224862725),
        },
        ["prism_lion"] = {
            ["basic"] = id(97995562975789),
            ["golden"] = id(131299751160380),
            ["rainbow"] = id(97995562975789),
        },
        ["prism_scarab"] = {
            ["basic"] = id(85274024869303),
            ["golden"] = id(136581823639554),
            ["rainbow"] = id(85274024869303),
        },
        ["radiant_salamander"] = {
            ["basic"] = id(116236822477663),
            ["golden"] = id(101998578414175),
            ["rainbow"] = id(116236822477663),
        },
        ["radiant_sprite"] = {
            ["basic"] = id(80509064603455),
            ["golden"] = id(105430802613104),
            ["rainbow"] = id(80509064603455),
        },
        ["rime_scarab"] = {
            ["basic"] = id(79924357335974),
            ["golden"] = id(134282463972631),
            ["rainbow"] = id(79924357335974),
        },
        ["rimegloom_hare"] = {
            ["basic"] = id(84955292995146),
            ["golden"] = id(131767826204802),
            ["rainbow"] = id(84955292995146),
        },
        ["rimeguard_bear"] = {
            ["basic"] = id(101358568386477),
            ["golden"] = id(92367699214651),
            ["rainbow"] = id(101358568386477),
        },
        ["rimelight_hare"] = {
            ["basic"] = id(92288518486682),
            ["golden"] = id(101563875213032),
            ["rainbow"] = id(92288518486682),
        },
        ["rimemane_lion"] = {
            ["basic"] = id(115227667542417),
            ["golden"] = id(112453751151966),
            ["rainbow"] = id(115227667542417),
        },
        ["rimewither_sprite"] = {
            ["basic"] = id(128908090207793),
            ["golden"] = id(91728510513031),
            ["rainbow"] = id(128908090207793),
        },
        ["rimewraith_dragon"] = {
            ["basic"] = id(83126391239112),
            ["golden"] = id(120166367353336),
            ["rainbow"] = id(83126391239112),
        },
        ["rimewraith_fox"] = {
            ["basic"] = id(97398697322604),
            ["golden"] = id(71000993149643),
            ["rainbow"] = id(97398697322604),
        },
        ["rotleaf_stag"] = {
            ["basic"] = id(120424701447302),
            ["golden"] = id(81220177210733),
            ["rainbow"] = id(120424701447302),
        },
        ["seraph_owl"] = {
            ["basic"] = id(83432339015268),
            ["golden"] = id(100615512051791),
            ["rainbow"] = id(83432339015268),
        },
        ["solar_phoenix"] = {
            ["basic"] = id(132304635491245),
            ["golden"] = id(136475446301158),
            ["rainbow"] = id(132304635491245),
        },
        ["solar_roc"] = {
            ["basic"] = id(123477410837004),
            ["golden"] = id(112634269821853),
            ["rainbow"] = id(123477410837004),
        },
        ["starlight_owl"] = {
            ["basic"] = id(84553579808261),
            ["golden"] = id(107624737169877),
            ["rainbow"] = id(84553579808261),
        },
        ["sun_scarab"] = {
            ["basic"] = id(137439384008786),
            ["golden"] = id(90568265537668),
            ["rainbow"] = id(137439384008786),
        },
        ["sunmane_lion"] = {
            ["basic"] = id(98489938311290),
            ["golden"] = id(131905924672983),
            ["rainbow"] = id(98489938311290),
        },
        ["sunwell_camel"] = {
            ["basic"] = id(79127150108268),
            ["golden"] = id(140601733762566),
            ["rainbow"] = id(79127150108268),
        },
        ["verdant_sprite"] = {
            ["basic"] = id(139619918066914),
            ["golden"] = id(95516570341344),
            ["rainbow"] = id(139619918066914),
        },
        ["wither_sprite"] = {
            ["basic"] = id(134787295000636),
            ["golden"] = id(132375057320160),
            ["rainbow"] = id(134787295000636),
        },
        ["worldbloom_ent"] = {
            ["basic"] = id(99308212873511),
            ["golden"] = id(78707189232086),
            ["rainbow"] = id(99308212873511),
        },
        ["worldroot_ent"] = {
            ["basic"] = id(95096456274476),
            ["golden"] = id(77606164465813),
            ["rainbow"] = id(95096456274476),
        },
        ["wraith_dove"] = {
            ["basic"] = id(101697025544772),
            ["golden"] = id(107349510202334),
            ["rainbow"] = id(101697025544772),
        },
    },
    eggs = {},
}
