--[[
    pet_thumbnail_assets — GENERATED by scripts/gen_pet_thumbnails.js from
    scripts/pet_thumbnail_ids.json. DO NOT EDIT BY HAND. Re-run `mise run gen-pet-thumbnails`
    after uploading/resolving thumbnails (scripts/upload_pet_thumbnails.js).

    Resolved flat IMAGE content ids for inventory-card thumbnails. The card prefers these
    (a texture — no per-frame ViewportFrame render) and falls back to the baked ViewportFrame
    when an id is absent. pets[petType][variant] / pets[petType][variant__huge] / eggs[eggType].
]]

local function id(n)
    return "rbxassetid://" .. n
end

return {
    pets = {
        ["abyssal_wyrm"] = {
            ["basic"] = id(76852321722613),
        },
        ["ash_roc"] = {
            ["basic"] = id(96778214828749),
        },
        ["ashmane_lion"] = {
            ["basic"] = id(121145811914516),
        },
    },
    eggs = {},
}
