#!/usr/bin/env node
/*
  build_pet_thumbnail_registry.js — assemble scripts/pet_thumbnail_ids.json from the bulk
  thumbnail upload + Decal->Image resolve, keyed by the AUTHORITATIVE config petType/variant.

  Inputs (all default under /tmp, override with flags):
    --basic   stem->decalId map from `upload_icons.js --dir front/basic` (default /tmp/thumb_basic.json)
    --gold    stem->decalId map from `upload_icons.js --dir front/gold`  (default /tmp/thumb_gold.json)
    --resolve decalId->imageId map from the Studio resolve step          (default /tmp/thumb_resolve.json)
    --out     SSOT to write                                              (default scripts/pet_thumbnail_ids.json)

  Mapping rules (configs/pets.lua is authoritative for names):
    render stem "<pet>_basic" -> pets.<pet>.basic
    render stem "<pet>_gold"  -> pets.<pet>.golden   (render "gold" == config "golden")
    pets.<pet>.rainbow = pets.<pet>.basic            (rainbow is an inventory background + an in-game
                                                       outline-recolor script, not its own render)
  A render whose <pet> is not a config petType is SKIPPED and listed under "mismatches" (reconcile the
  name in configs/pets.lua or here, then re-run — the upload id is reused, no re-upload).

  Usage: node scripts/build_pet_thumbnail_registry.js [--basic ...] [--gold ...] [--resolve ...]
*/
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const argv = process.argv.slice(2);
const arg = (k, d) => {
  const i = argv.indexOf("--" + k);
  return i >= 0 && argv[i + 1] ? argv[i + 1] : d;
};
const BASIC = path.resolve(arg("basic", "/tmp/thumb_basic.json"));
const GOLD = path.resolve(arg("gold", "/tmp/thumb_gold.json"));
const RESOLVE = path.resolve(arg("resolve", "/tmp/thumb_resolve.json"));
const OUT = path.resolve(ROOT, arg("out", "scripts/pet_thumbnail_ids.json"));
const PETS_LUA = path.join(ROOT, "configs", "pets.lua");

const readJson = (p) => (fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, "utf8")) : {});

// Authoritative config petType keys = the DIRECT children of the `pets = { ... }` table. Brace-bounded
// so it stops at the table's close (an unbounded indent-8 scan bleeds into sibling tables like
// egg_sources/abilities and falsely admits ability/egg names).
function configPetTypes() {
  const src = fs.readFileSync(PETS_LUA, "utf8");
  const m = src.match(/\n {4}pets = \{/);
  const keys = new Set();
  if (m) {
    let depth = 1;
    for (const line of src.slice(m.index + m[0].length).split("\n")) {
      if (depth === 1) {
        const k = line.match(/^ {8}([a-z][a-z0-9_]*) = \{/);
        if (k) keys.add(k[1]);
      }
      depth += (line.split("{").length - 1) - (line.split("}").length - 1);
      if (depth <= 0) break;
    }
  }
  return keys;
}

const basicMap = readJson(BASIC); // stem(<pet>_basic) -> decalId
const goldMap = readJson(GOLD); // stem(<pet>_gold)  -> decalId
const resolve = readJson(RESOLVE); // decalId -> imageId
const petTypes = configPetTypes();

function imageFor(decalId) {
  const img = resolve[String(decalId)];
  return img && /^\d+$/.test(String(img)) ? Number(img) : null;
}

const pets = {};
const mismatches = [];
let basicCount = 0,
  goldCount = 0,
  unresolved = 0;

function ingest(map, suffix, variant) {
  for (const [stem, decal] of Object.entries(map)) {
    if (!stem.endsWith(suffix)) continue;
    const pet = stem.slice(0, -suffix.length);
    if (!petTypes.has(pet)) {
      mismatches.push(stem);
      continue;
    }
    const img = imageFor(decal);
    if (!img) {
      unresolved += 1;
      continue;
    }
    pets[pet] = pets[pet] || {};
    pets[pet][variant] = img;
    if (variant === "basic") basicCount += 1;
    else goldCount += 1;
  }
}
ingest(basicMap, "_basic", "basic");
ingest(goldMap, "_gold", "golden");

// rainbow rides the basic texture (the rainbow look is card chrome / spawn-side outline recolor).
let rainbowCount = 0;
for (const [pet, v] of Object.entries(pets)) {
  if (v.basic && !v.rainbow) {
    v.rainbow = v.basic;
    rainbowCount += 1;
  }
}

const existing = readJson(OUT);
const out = {
  _comment:
    existing._comment ||
    "GENERATED by build_pet_thumbnail_registry.js. SSOT for pet card thumbnails (group-owned IMAGE ids). Consumed by gen_pet_thumbnails.js. Keys are config petType/variant.",
  pets: Object.fromEntries(Object.keys(pets).sort().map((k) => [k, pets[k]])),
  eggs: existing.eggs || {},
};
fs.writeFileSync(OUT, JSON.stringify(out, null, 2) + "\n");

console.log(
  `wrote ${path.relative(ROOT, OUT)}: ${basicCount} basic, ${goldCount} gold, ${rainbowCount} rainbow(=basic) across ${Object.keys(pets).length} pets.`
);
if (unresolved) console.log(`  ${unresolved} decals had no resolved image (run the resolve step).`);
if (mismatches.length) console.log(`  ${mismatches.length} render names not in config (skipped): ${mismatches.sort().join(", ")}`);
