#!/usr/bin/env node
/*
  gen_power_icons.js — GENERATE configs/power_icons_assets.lua from scripts/asset_manifest.json.

  The manifest (scripts/asset_manifest.json) is the single source of truth for asset ids. This
  emits a Lua module with the resolved IMAGE ids only (the Decal ids do NOT render in ImageLabel.
  Image). configs/power_icons.lua require()s this module for its discs/rings tables and keeps the
  hand-written helpers/maps. DO NOT hand-edit the generated file — re-run `mise run gen-icons`.

  Disc COLOR -> badge ELEMENT key:
    green->earth, red->fire, yellow->desert, blue->ice, white->neutral (the generic/universal tier).
  Ring keys: strip the "ring_" prefix (ring_target_in -> target_in, ...).

  Output is deterministic (sorted keys) so re-running is idempotent (git-stable).

  Usage: node scripts/gen_power_icons.js
*/
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const MANIFEST = path.join(ROOT, "scripts", "asset_manifest.json");
const OUT = path.join(ROOT, "configs", "power_icons_assets.lua");

const COLOR_TO_ELEMENT = {
  green: "earth",
  red: "fire",
  yellow: "desert",
  blue: "ice",
  white: "neutral",
};
// Emit elements in a stable order.
const ELEMENT_ORDER = ["earth", "fire", "desert", "ice", "neutral"];

const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));

// ---- discs[element][symbol] = image id (only resolved entries) ----
const discsByElement = {};
let discCount = 0,
  discUnresolved = 0;
for (const [color, element] of Object.entries(COLOR_TO_ELEMENT)) {
  const bucket = (manifest.discs && manifest.discs[color]) || {};
  for (const [symbol, rec] of Object.entries(bucket)) {
    if (symbol.startsWith("_")) continue;
    if (!rec || !rec.image) {
      discUnresolved += 1;
      continue;
    }
    discsByElement[element] = discsByElement[element] || {};
    discsByElement[element][symbol] = String(rec.image);
    discCount += 1;
  }
}

// ---- rings[shape] = image id ----
const rings = {};
for (const [key, rec] of Object.entries(manifest.rings || {})) {
  if (key.startsWith("_")) continue;
  if (!rec || !rec.image) continue;
  rings[key.replace(/^ring_/, "")] = String(rec.image);
}

// ---- emit Lua ----
const L = [];
L.push("--[[");
L.push("    power_icons_assets — GENERATED by scripts/gen_power_icons.js from scripts/asset_manifest.json.");
L.push("    DO NOT EDIT BY HAND. Re-run `mise run gen-icons` after uploading/resolving icons.");
L.push("");
L.push("    Resolved IMAGE content ids (not Decal ids). discs[element][symbol] + rings[shape].");
L.push("    Disc colour -> element: green=earth, red=fire, yellow=desert, blue=ice, white=neutral.");
L.push("]]");
L.push("");
L.push("local function id(n)");
L.push('    return "rbxassetid://" .. n');
L.push("end");
L.push("");
L.push("return {");
L.push("    discs = {");
for (const element of ELEMENT_ORDER) {
  const syms = discsByElement[element];
  if (!syms) continue;
  L.push(`        ${element} = {`);
  for (const symbol of Object.keys(syms).sort()) {
    L.push(`            ${symbol} = id(${syms[symbol]}),`);
  }
  L.push("        },");
}
L.push("    },");
L.push("    rings = {");
for (const shape of Object.keys(rings).sort()) {
  L.push(`        ${shape} = id(${rings[shape]}),`);
}
L.push("    },");
L.push("}");
L.push("");

fs.writeFileSync(OUT, L.join("\n"));
console.log(
  `wrote ${path.relative(ROOT, OUT)}: ${discCount} discs (${discUnresolved} unresolved skipped), ${Object.keys(rings).length} rings.`
);
