#!/usr/bin/env node
/*
  gen_pet_thumbnails.js — GENERATE configs/pet_thumbnail_assets.lua from scripts/pet_thumbnail_ids.json.

  The json (scripts/pet_thumbnail_ids.json) is the single source of truth for pre-uploaded pet/egg
  card THUMBNAIL image ids. This emits a Lua module of the resolved IMAGE ids only — the inventory
  card (InventoryPanel:_getPetImageFromAssets) prefers a flat ImageLabel from this registry and only
  falls back to cloning the baked ViewportFrame when an id is missing. Same shape as the icon codegen
  (gen_power_icons.js -> power_icons_assets.lua): the generated file is require()'d directly from
  ReplicatedStorage.Configs, NOT through ConfigLoader, so it needs no schema.

  Mirrors the upload pipeline's "resolve in-engine, paste back" loop: scripts/upload_pet_thumbnails.js
  uploads rendered PNGs and writes ids here; this turns them into Lua. DO NOT hand-edit the generated
  file — re-run `mise run gen-pet-thumbnails`.

  Registry shape (only entries with a numeric id are emitted; unresolved are skipped):
    pets["<petType>"]["<variant>"]         = id(<n>)   -- normal framed thumbnail
    pets["<petType>"]["<variant>__huge"]   = id(<n>)   -- up-close HUGE-framed thumbnail
    eggs["<eggType>"]                      = id(<n>)

  Output is deterministic (sorted keys) so re-running is idempotent (git-stable).

  Usage: node scripts/gen_pet_thumbnails.js
*/
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "scripts", "pet_thumbnail_ids.json");
const OUT = path.join(ROOT, "configs", "pet_thumbnail_assets.lua");

const data = JSON.parse(fs.readFileSync(SRC, "utf8"));

// A valid, positive integer asset id? (strings and numbers both accepted; "" / null / 0 are skipped.)
function resolvedId(v) {
  if (v === null || v === undefined) return null;
  const n = Number(v);
  if (!Number.isFinite(n) || n <= 0 || Math.floor(n) !== n) return null;
  return String(n);
}

// ---- pets[petType][variantKey] = id ----
const pets = {};
let petCount = 0;
for (const [petType, byVariant] of Object.entries(data.pets || {})) {
  if (petType.startsWith("_") || typeof byVariant !== "object" || !byVariant) continue;
  for (const [variantKey, raw] of Object.entries(byVariant)) {
    if (variantKey.startsWith("_")) continue;
    const id = resolvedId(raw);
    if (!id) continue;
    pets[petType] = pets[petType] || {};
    pets[petType][variantKey] = id;
    petCount += 1;
  }
}

// ---- eggs[eggType] = id ----
const eggs = {};
let eggCount = 0;
for (const [eggType, raw] of Object.entries(data.eggs || {})) {
  if (eggType.startsWith("_")) continue;
  const id = resolvedId(raw);
  if (!id) continue;
  eggs[eggType] = id;
  eggCount += 1;
}

// ---- emit Lua (bracket-quoted keys: petType/variant come from config strings, not guaranteed idents) ----
const L = [];
L.push("--[[");
L.push("    pet_thumbnail_assets — GENERATED by scripts/gen_pet_thumbnails.js from");
L.push("    scripts/pet_thumbnail_ids.json. DO NOT EDIT BY HAND. Re-run `mise run gen-pet-thumbnails`");
L.push("    after uploading/resolving thumbnails (scripts/upload_pet_thumbnails.js).");
L.push("");
L.push("    Resolved flat IMAGE content ids for inventory-card thumbnails. The card prefers these");
L.push("    (a texture — no per-frame ViewportFrame render) and falls back to the baked ViewportFrame");
L.push("    when an id is absent. pets[petType][variant] / pets[petType][variant__huge] / eggs[eggType].");
L.push("]]");
L.push("");
// Only emit the id() helper when something uses it — an unused local trips selene's unused_variable
// while the registry is still empty (before the first upload pass).
if (petCount + eggCount > 0) {
  L.push("local function id(n)");
  L.push('    return "rbxassetid://" .. n');
  L.push("end");
  L.push("");
}
L.push("return {");
L.push("    pets = {");
for (const petType of Object.keys(pets).sort()) {
  L.push(`        ["${petType}"] = {`);
  for (const variantKey of Object.keys(pets[petType]).sort()) {
    L.push(`            ["${variantKey}"] = id(${pets[petType][variantKey]}),`);
  }
  L.push("        },");
}
L.push("    },");
L.push("    eggs = {");
for (const eggType of Object.keys(eggs).sort()) {
  L.push(`        ["${eggType}"] = id(${eggs[eggType]}),`);
}
L.push("    },");
L.push("}");
L.push("");

fs.writeFileSync(OUT, L.join("\n"));
console.log(
  `wrote ${path.relative(ROOT, OUT)}: ${petCount} pet thumbnails, ${eggCount} egg thumbnails.`
);
