#!/usr/bin/env bash
# Stamp configs/build_info.lua from git + the current Mountain Time, so the
# in-game loading screen shows EXACTLY which commit is running and when it was
# built (Jason: "if I publish and something's not working I can tell if it
# updated"). Run before any build/publish; rojo syncs the file into Studio.
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION="$(tr -d '[:space:]' < VERSION 2>/dev/null || echo '0.0.0')"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')"
# git formats the dates itself (cross-platform: macOS + Linux/CI), TZ -> Mountain
COMMIT_DATE="$(TZ='America/Denver' git show -s --format='%cd' \
  --date=format-local:'%Y-%m-%d %I:%M %p %Z' HEAD 2>/dev/null || echo 'unknown')"
BUILT_AT="$(TZ='America/Denver' date '+%Y-%m-%d %I:%M %p %Z')"
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then DIRTY="true"; else DIRTY="false"; fi

cat > configs/build_info.lua <<LUA
--[[
    build_info — GENERATED by scripts/stamp_build.sh (mise run stamp). Do NOT
    hand-edit: it's overwritten on every build/publish. Shows on the BootLoader
    load screen so a published build is identifiable at a glance. Times are
    Mountain (America/Denver, DST-correct). Committed with the LAST stamp so dev
    sessions / CI have a value; the publish tasks re-stamp it fresh.
]]
return {
    version = "$VERSION",
    commit = "$COMMIT",
    branch = "$BRANCH",
    commit_date = "$COMMIT_DATE", -- when the running code was committed
    built_at = "$BUILT_AT", -- when this build was stamped (publish time)
    dirty = $DIRTY, -- uncommitted changes present at stamp time
}
LUA
echo "[stamp] v$VERSION  $COMMIT ($BRANCH)  built $BUILT_AT  dirty=$DIRTY"
